//1
SELECT * FROM JOBS
WHERE MIN_SALARY>10000;
//2
SELECT FIRST_NAME,HIRE_DATE FROM EMPLOYEES
WHERE EXTRACT(YEAR FROM HIRE_DATE) BETWEEN 1980 AND 1995;
//3
SELECT FIRST_NAME,HIRE_DATE FROM EMPLOYEES
WHERE JOB_ID= 'IT_PROG' OR JOB_ID ='SA_MAN';
//4
SELECT * FROM EMPLOYEES  where hire_date > '01-jan-2008';
//5
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID in (150,160);
//6
SELECT FIRST_NAME,SALARY,COMMISION_PCT,HIRE_DATE FROM EMPLOYEES
WHERE SALARY<10000;
//7
SELECT JOB_TITLE, MAX_SALARY-MIN_SALARY DIFFERENCE FROM JOBS WHERE MAX_SALARY BETWEEN 10000 AND 20000;
//8
SELECT FIRST_NAME, SALARY, ROUND(SALARY, -3) FROM EMPLOYEES;
//9
SELECT * FROM JOBS
ORDER BY job_title DESC;
//10
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE  FIRST_NAME  LIKE 'S%' OR LAST_NAME  LIKE 'S%';
//11
SELECT * FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'MON')= 'MAY';
//12
SELECT * FROM EMPLOYEES WHERE COMMISION_PCT IS NULL AND SALARY BETWEEN 5000 AND 10000 AND DEPARTMENT_ID=30;
//13
SELECT FIRST_NAME, HIRE_DATE, LAST_DAY(HIRE_DATE)+1 FROM EMPLOYEES;
//14
SELECT FIRST_NAME, HIRE_DATE, FLOOR((SYSDATE-HIRE_DATE)/365)FROM EMPLOYEES;
//15
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE EXTRACT(YEAR FROM HIRE_DATE)=2000;
//16
sELECT INITCAP(FIRST_NAME),INITCAP(LAST_NAME) FROM EMPLOYEES;
/17
SELECT JOB_TITLE,  SUBSTR(JOB_TITLE,1, INSTR(JOB_TITLE, ' ')-1) FROM JOBS;
//18
SELECT LENGTH(FIRST_NAME) FROM EMPLOYEES WHERE INSTR(LAST_NAME,'b') > 3;
//19
SELECT UPPER(FIRST_NAME), LOWER(EMAIL) FROM EMPLOYEES WHERE UPPER(FIRST_NAME)= UPPER(EMAIL);
//20
SELECT * FROM EMPLOYEES WHERE EXTRACT(YEAR FROM HIRE_DATE)=2000;
//21
SELECT SYSDATE - to_date('01-jan-2011') FROM DUAL;
//22
SELECT TO_CHAR(HIRE_DATE,'MM'), COUNT (*) FROM EMPLOYEES 
WHERE TO_CHAR(HIRE_DATE,'YYYY')= 2000 GROUP BY TO_CHAR(HIRE_DATE,'MM') ;
//23
SELECT MANAGER_ID, COUNT(*) FROM EMPLOYEES GROUP BY MANAGER_ID;
//24
SELECT EMPLOYEE_ID, START_DATE-1 FROM JOB_HISTORY; 
//25
SELECT * FROM EMPLOYEES WHERE EXTRACT(DAY FROM HIRE_DATE) >15;
//26
SELECT COUNTRY_ID,COUNT(*) FROM LOCATIONS GROUP BY COUNTRY_ID;
//27
SELECT DEPARTMENT_ID, AVG(SALARY) FROM EMPLOYEES 
WHERE COMMISION_PCT IS NOT NULL GROUP BY DEPARTMENT_ID;
//28
SELECT JOB_ID, COUNT(*), SUM(SALARY), MAX(SALARY)-MIN(SALARY) SALARY FROM EMPLOYEES GROUP BY JOB_ID;
//29
SELECT JOB_ID FROM EMPLOYEES GROUP BY JOB_ID HAVING AVG(SALARY)>10000;
//30
SELECT TO_CHAR(HIRE_DATE,'YYYY') FROM EMPLOYEES 
GROUP BY TO_CHAR(HIRE_DATE,'YYYY') 
HAVING COUNT(EMPLOYEE_ID) > 10;
//31
SELECT DEPARTMENT_ID FROM EMPLOYEES 
WHERE COMMISION_PCT IS NOT NULL
GROUP BY DEPARTMENT_ID 
HAVING COUNT(COMMISION_PCT)>5;
//32
SELECT EMPLOYEE_ID FROM JOB_HISTORY GROUP BY EMPLOYEE_ID HAVING COUNT(*) > 1;
//33
SELECT JOB_ID FROM JOB_HISTORY
WHERE  (END_DATE-START_DATE)>100
GROUP BY JOB_ID
HAVING COUNT(*)>3 ;
//34
SELECT department_id,EXTRACT(YEAR FROM HIRE_DATE),COUNT(EMPLOYEE_ID) from employees GROUP BY DEPARTMENT_ID,EXTRACT(YEAR FROM HIRE_DATE) ;
//35
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID,MANAGER_ID HAVING COUNT(EMPLOYEE_ID)>5;
//36
UPDATE EMPLOYEES SET SALARY = 8000 WHERE EMPLOYEE_ID = 115 AND SALARY < 6000;
//37
INSERT INTO EMPLOYEES  (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE,JOB_ID, SALARY, DEPARTMENT_ID) 
VALUES (207, 'ANGELA', 'SNYDER','ANGELA','215 253 4737', SYSDATE, 'SA_MAN', 12000, 80);
//38
DELETE FROM DEPARTMENT WHERE DEPARTMENT_ID=20;
//39
UPDATE EMPLOYEES SET JOB_ID='IT_PROG' WHERE DEPARTMENT_ID=10 AND EMPLOYEE_ID=110 AND NOT JOB_ID LIKE 'IT%';
//40
INSERT INTO DEPARTMENTS VALUES (1234,'SPORTS',120,1200);
//41
SELECT DEPARTMENT_NAME,COUNT(*) FROM EMPLOYEES
NATURAL JOIN DEPARTMENTS
GROUP BY DEPARTMENT_NAME;
//42
SELECT JOB_ID,EMPLOYEE_ID, END_DATE-START_DATE FROM JOB_HISTORY WHERE DEPARTMENT_ID=30;  
//43
SELECT D.DEPARTMENT_NAME,E.FIRST_NAME FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON D.DEPARTMENT_ID=E.DEPARTMENT_ID;
//44
SELECT D.DEPARTMENT_NAME,E.FIRST_NAME,L.CITY FROM DEPARTMENTS D
 JOIN  EMPLOYEES E
ON D.MANAGER_ID=E.EMPLOYEE_ID
 JOIN LOCATIONS L
ON D.LOCATION_ID=L.LOCATION_ID;
//45
SELECT CO.COUNTRY_NAME,L.CITY,D.DEPARTMENT_NAME FROM LOCATIONS L
INNER JOIN DEPARTMENTS D
ON D.LOCATION_ID=L.LOCATION_ID
INNER JOIN COUNTRIES CO
ON CO.COUNTRY_ID=L.COUNTRY_ID;
//46
SELECT JO.JOB_TITLE,D.DEPARTMENT_NAME,E.LAST_NAME,J.START_DATE 
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON D.DEPARTMENT_ID=E.DEPARTMENT_ID
INNER JOIN JOB_HISTORY J
ON J.EMPLOYEE_ID=E.EMPLOYEE_ID
INNER JOIN JOBS JO
ON JO.JOB_ID=E.JOB_ID
WHERE EXTRACT(YEAR FROM J.START_DATE) BETWEEN 1990 AND 2000;
//47
SELECT JO.JOB_TITLE, AVG(E.SALARY)
FROM EMPLOYEES E
INNER JOIN JOBS JO
ON JO.JOB_ID=E.JOB_ID
GROUP BY JO.JOB_TITLE;
//48
SELECT JOB_TITLE, FIRST_NAME, MAX_SALARY-SALARY DIFFERENCE FROM EMPLOYEES NATURAL JOIN JOBS;
//49
SELECT E.LAST_NAME,J.JOB_TITLE
FROM EMPLOYEES E
INNER JOIN JOBS J
ON J.JOB_ID=E.JOB_ID
WHERE NOT COMMISION_PCT LIKE NULL
AND DEPARTMENT_ID=30;
//50
SELECT JH.* FROM JOB_HISTORY JH
INNER JOIN EMPLOYEES E
ON E.JOB_ID=JH.JOB_ID
WHERE E.SALARY>15000;
